/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.api;

import cloud.neice.ApiException;
import cloud.neice.model.OutResponseOfBalance;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalanceApi
 */
@Ignore
public class BalanceApiTest {

    private final BalanceApi api = new BalanceApi();

    
    /**
     * 获取用户余额
     *
     * 获取用户余额
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBalanceTest() throws ApiException {
        OutResponseOfBalance response = api.getBalance();

        // TODO: test validations
    }
    
}
