/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.api;

import cloud.neice.ApiException;
import cloud.neice.model.DeviceRequest;
import cloud.neice.model.OutResponseOfListOfPersonalCertificate;
import cloud.neice.model.OutResponseOfPersonalCertificate;
import cloud.neice.model.OutResponseOfStatus;
import cloud.neice.model.OutResponseOfstring;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceApi
 */
@Ignore
public class DeviceApiTest {

    private final DeviceApi api = new DeviceApi();

    
    /**
     * 获取iOS设备证书
     *
     * 获取iOS设备证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificateTest() throws ApiException {
        String udid = null;
        OutResponseOfPersonalCertificate response = api.getCertificate(udid);

        // TODO: test validations
    }
    
    /**
     * 获取iOS设备证书列表
     *
     * 获取iOS设备证书列表
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificatesTest() throws ApiException {
        Integer limit = null;
        Integer page = null;
        Boolean asc = null;
        OutResponseOfListOfPersonalCertificate response = api.getCertificates(limit, page, asc);

        // TODO: test validations
    }
    
    /**
     * 获取证书支持类型
     *
     * 获取证书支持类型
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatusTest() throws ApiException {
        OutResponseOfStatus response = api.getStatus();

        // TODO: test validations
    }
    
    /**
     * iOS设备注册
     *
     * iOS设备注册
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerTest() throws ApiException {
        DeviceRequest request = null;
        OutResponseOfPersonalCertificate response = api.register(request);

        // TODO: test validations
    }
    
    /**
     * iOS设备批量提交注册
     *
     * 请确保批量提交的数据的准性，提交后不可撤销，批量提交注册将不直接返回证书，请通过回调接口接收证书，如果没提供回调接口，可使用查询接口查询
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registersTest() throws ApiException {
        List<DeviceRequest> deviceRequests = null;
        OutResponseOfstring response = api.registers(deviceRequests);

        // TODO: test validations
    }
    
}
