/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.api;

import cloud.neice.ApiException;
import cloud.neice.model.CertificateRequest;
import cloud.neice.model.ResponseOfListOfCertificateResponse;
import cloud.neice.model.ResponseOfListOfOpenEnterpriseCertificate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenApi
 */
@Ignore
public class OpenApiTest {

    private final OpenApi api = new OpenApi();

    
    /**
     * 获取开发的iOS设备证书
     *
     * 获取开发的iOS设备证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificate1Test() throws ApiException {
        String udid = null;
        String code = null;
        ResponseOfListOfCertificateResponse response = api.getCertificate1(udid, code);

        // TODO: test validations
    }
    
    /**
     * 获取开发的iOS设备证书
     *
     * 获取开发的iOS设备证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificate2Test() throws ApiException {
        String udid = null;
        ResponseOfListOfCertificateResponse response = api.getCertificate2(udid);

        // TODO: test validations
    }
    
    /**
     * 获取开发的iOS设备证书
     *
     * 获取开发的iOS设备证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificate3Test() throws ApiException {
        String udid = null;
        ResponseOfListOfCertificateResponse response = api.getCertificate3(udid);

        // TODO: test validations
    }
    
    /**
     * 获取开发的iOS设备证书
     *
     * 获取开发的iOS设备证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificate4Test() throws ApiException {
        CertificateRequest request = null;
        ResponseOfListOfCertificateResponse response = api.getCertificate4(request);

        // TODO: test validations
    }
    
    /**
     * 获取企业开发者证书
     *
     * 获取企业开发者证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEnterpriseCertificatesTest() throws ApiException {
        ResponseOfListOfOpenEnterpriseCertificate response = api.getEnterpriseCertificates();

        // TODO: test validations
    }
    
    /**
     * 获取企业开发者证书
     *
     * 获取企业开发者证书
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEnterpriseCertificates1Test() throws ApiException {
        ResponseOfListOfOpenEnterpriseCertificate response = api.getEnterpriseCertificates1();

        // TODO: test validations
    }
    
}
