/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.neice.JSON;

/**
 * Balance
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Balance {
  public static final String SERIALIZED_NAME_ACQUIRE = "acquire";
  @SerializedName(SERIALIZED_NAME_ACQUIRE)
  @jakarta.annotation.Nullable
  private BigDecimal acquire;

  public static final String SERIALIZED_NAME_ALGORITHM = "algorithm";
  @SerializedName(SERIALIZED_NAME_ALGORITHM)
  @jakarta.annotation.Nullable
  private String algorithm;

  public static final String SERIALIZED_NAME_BALANCE = "balance";
  @SerializedName(SERIALIZED_NAME_BALANCE)
  @jakarta.annotation.Nullable
  private BigDecimal balance;

  public static final String SERIALIZED_NAME_CIPHERTEXT = "ciphertext";
  @SerializedName(SERIALIZED_NAME_CIPHERTEXT)
  @jakarta.annotation.Nullable
  private String ciphertext;

  public static final String SERIALIZED_NAME_ESCROW = "escrow";
  @SerializedName(SERIALIZED_NAME_ESCROW)
  @jakarta.annotation.Nullable
  private BigDecimal escrow;

  public static final String SERIALIZED_NAME_REWARD = "reward";
  @SerializedName(SERIALIZED_NAME_REWARD)
  @jakarta.annotation.Nullable
  private BigDecimal reward;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  @jakarta.annotation.Nullable
  private String session;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @jakarta.annotation.Nullable
  private BigDecimal total;

  public static final String SERIALIZED_NAME_USER_UUID = "userUuid";
  @SerializedName(SERIALIZED_NAME_USER_UUID)
  @jakarta.annotation.Nullable
  private String userUuid;

  public static final String SERIALIZED_NAME_VOUCHER = "voucher";
  @SerializedName(SERIALIZED_NAME_VOUCHER)
  @jakarta.annotation.Nullable
  private BigDecimal voucher;

  public Balance() {
  }

  public Balance acquire(@jakarta.annotation.Nullable BigDecimal acquire) {
    this.acquire = acquire;
    return this;
  }

  /**
   * Get acquire
   * @return acquire
   */
  @jakarta.annotation.Nullable
  public BigDecimal getAcquire() {
    return acquire;
  }

  public void setAcquire(@jakarta.annotation.Nullable BigDecimal acquire) {
    this.acquire = acquire;
  }


  public Balance algorithm(@jakarta.annotation.Nullable String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

  /**
   * Get algorithm
   * @return algorithm
   */
  @jakarta.annotation.Nullable
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(@jakarta.annotation.Nullable String algorithm) {
    this.algorithm = algorithm;
  }


  public Balance balance(@jakarta.annotation.Nullable BigDecimal balance) {
    this.balance = balance;
    return this;
  }

  /**
   * Get balance
   * @return balance
   */
  @jakarta.annotation.Nullable
  public BigDecimal getBalance() {
    return balance;
  }

  public void setBalance(@jakarta.annotation.Nullable BigDecimal balance) {
    this.balance = balance;
  }


  public Balance ciphertext(@jakarta.annotation.Nullable String ciphertext) {
    this.ciphertext = ciphertext;
    return this;
  }

  /**
   * Get ciphertext
   * @return ciphertext
   */
  @jakarta.annotation.Nullable
  public String getCiphertext() {
    return ciphertext;
  }

  public void setCiphertext(@jakarta.annotation.Nullable String ciphertext) {
    this.ciphertext = ciphertext;
  }


  public Balance escrow(@jakarta.annotation.Nullable BigDecimal escrow) {
    this.escrow = escrow;
    return this;
  }

  /**
   * Get escrow
   * @return escrow
   */
  @jakarta.annotation.Nullable
  public BigDecimal getEscrow() {
    return escrow;
  }

  public void setEscrow(@jakarta.annotation.Nullable BigDecimal escrow) {
    this.escrow = escrow;
  }


  public Balance reward(@jakarta.annotation.Nullable BigDecimal reward) {
    this.reward = reward;
    return this;
  }

  /**
   * Get reward
   * @return reward
   */
  @jakarta.annotation.Nullable
  public BigDecimal getReward() {
    return reward;
  }

  public void setReward(@jakarta.annotation.Nullable BigDecimal reward) {
    this.reward = reward;
  }


  public Balance session(@jakarta.annotation.Nullable String session) {
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @jakarta.annotation.Nullable
  public String getSession() {
    return session;
  }

  public void setSession(@jakarta.annotation.Nullable String session) {
    this.session = session;
  }


  public Balance total(@jakarta.annotation.Nullable BigDecimal total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @jakarta.annotation.Nullable
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(@jakarta.annotation.Nullable BigDecimal total) {
    this.total = total;
  }


  public Balance userUuid(@jakarta.annotation.Nullable String userUuid) {
    this.userUuid = userUuid;
    return this;
  }

  /**
   * Get userUuid
   * @return userUuid
   */
  @jakarta.annotation.Nullable
  public String getUserUuid() {
    return userUuid;
  }

  public void setUserUuid(@jakarta.annotation.Nullable String userUuid) {
    this.userUuid = userUuid;
  }


  public Balance voucher(@jakarta.annotation.Nullable BigDecimal voucher) {
    this.voucher = voucher;
    return this;
  }

  /**
   * Get voucher
   * @return voucher
   */
  @jakarta.annotation.Nullable
  public BigDecimal getVoucher() {
    return voucher;
  }

  public void setVoucher(@jakarta.annotation.Nullable BigDecimal voucher) {
    this.voucher = voucher;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Balance balance = (Balance) o;
    return Objects.equals(this.acquire, balance.acquire) &&
        Objects.equals(this.algorithm, balance.algorithm) &&
        Objects.equals(this.balance, balance.balance) &&
        Objects.equals(this.ciphertext, balance.ciphertext) &&
        Objects.equals(this.escrow, balance.escrow) &&
        Objects.equals(this.reward, balance.reward) &&
        Objects.equals(this.session, balance.session) &&
        Objects.equals(this.total, balance.total) &&
        Objects.equals(this.userUuid, balance.userUuid) &&
        Objects.equals(this.voucher, balance.voucher);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquire, algorithm, balance, ciphertext, escrow, reward, session, total, userUuid, voucher);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Balance {\n");
    sb.append("    acquire: ").append(toIndentedString(acquire)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    ciphertext: ").append(toIndentedString(ciphertext)).append("\n");
    sb.append("    escrow: ").append(toIndentedString(escrow)).append("\n");
    sb.append("    reward: ").append(toIndentedString(reward)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    voucher: ").append(toIndentedString(voucher)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("acquire");
    openapiFields.add("algorithm");
    openapiFields.add("balance");
    openapiFields.add("ciphertext");
    openapiFields.add("escrow");
    openapiFields.add("reward");
    openapiFields.add("session");
    openapiFields.add("total");
    openapiFields.add("userUuid");
    openapiFields.add("voucher");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Balance
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Balance.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Balance is not found in the empty JSON string", Balance.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Balance.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Balance` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("algorithm") != null && !jsonObj.get("algorithm").isJsonNull()) && !jsonObj.get("algorithm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `algorithm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("algorithm").toString()));
      }
      if ((jsonObj.get("ciphertext") != null && !jsonObj.get("ciphertext").isJsonNull()) && !jsonObj.get("ciphertext").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ciphertext` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ciphertext").toString()));
      }
      if ((jsonObj.get("session") != null && !jsonObj.get("session").isJsonNull()) && !jsonObj.get("session").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `session` to be a primitive type in the JSON string but got `%s`", jsonObj.get("session").toString()));
      }
      if ((jsonObj.get("userUuid") != null && !jsonObj.get("userUuid").isJsonNull()) && !jsonObj.get("userUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userUuid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Balance.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Balance' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Balance> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Balance.class));

       return (TypeAdapter<T>) new TypeAdapter<Balance>() {
           @Override
           public void write(JsonWriter out, Balance value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Balance read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Balance given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Balance
   * @throws IOException if the JSON string is invalid with respect to Balance
   */
  public static Balance fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Balance.class);
  }

  /**
   * Convert an instance of Balance to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

