/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import cloud.neice.ApiClient;
/**
 * Balance
 */
@JsonPropertyOrder({
  Balance.JSON_PROPERTY_ALGORITHM,
  Balance.JSON_PROPERTY_BALANCE,
  Balance.JSON_PROPERTY_CIPHERTEXT,
  Balance.JSON_PROPERTY_ESCROW,
  Balance.JSON_PROPERTY_REWARD,
  Balance.JSON_PROPERTY_SESSION,
  Balance.JSON_PROPERTY_TOTAL,
  Balance.JSON_PROPERTY_USER_UUID,
  Balance.JSON_PROPERTY_VOUCHER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Balance {
  public static final String JSON_PROPERTY_ALGORITHM = "algorithm";
  @jakarta.annotation.Nullable
  private String algorithm;

  public static final String JSON_PROPERTY_BALANCE = "balance";
  @jakarta.annotation.Nullable
  private BigDecimal balance;

  public static final String JSON_PROPERTY_CIPHERTEXT = "ciphertext";
  @jakarta.annotation.Nullable
  private String ciphertext;

  public static final String JSON_PROPERTY_ESCROW = "escrow";
  @jakarta.annotation.Nullable
  private BigDecimal escrow;

  public static final String JSON_PROPERTY_REWARD = "reward";
  @jakarta.annotation.Nullable
  private BigDecimal reward;

  public static final String JSON_PROPERTY_SESSION = "session";
  @jakarta.annotation.Nullable
  private String session;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @jakarta.annotation.Nullable
  private BigDecimal total;

  public static final String JSON_PROPERTY_USER_UUID = "userUuid";
  @jakarta.annotation.Nullable
  private String userUuid;

  public static final String JSON_PROPERTY_VOUCHER = "voucher";
  @jakarta.annotation.Nullable
  private BigDecimal voucher;

  public Balance() { 
  }

  public Balance algorithm(@jakarta.annotation.Nullable String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

  /**
   * Get algorithm
   * @return algorithm
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAlgorithm() {
    return algorithm;
  }


  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlgorithm(@jakarta.annotation.Nullable String algorithm) {
    this.algorithm = algorithm;
  }


  public Balance balance(@jakarta.annotation.Nullable BigDecimal balance) {
    this.balance = balance;
    return this;
  }

  /**
   * Get balance
   * @return balance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBalance() {
    return balance;
  }


  @JsonProperty(JSON_PROPERTY_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBalance(@jakarta.annotation.Nullable BigDecimal balance) {
    this.balance = balance;
  }


  public Balance ciphertext(@jakarta.annotation.Nullable String ciphertext) {
    this.ciphertext = ciphertext;
    return this;
  }

  /**
   * Get ciphertext
   * @return ciphertext
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CIPHERTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCiphertext() {
    return ciphertext;
  }


  @JsonProperty(JSON_PROPERTY_CIPHERTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCiphertext(@jakarta.annotation.Nullable String ciphertext) {
    this.ciphertext = ciphertext;
  }


  public Balance escrow(@jakarta.annotation.Nullable BigDecimal escrow) {
    this.escrow = escrow;
    return this;
  }

  /**
   * Get escrow
   * @return escrow
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESCROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getEscrow() {
    return escrow;
  }


  @JsonProperty(JSON_PROPERTY_ESCROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEscrow(@jakarta.annotation.Nullable BigDecimal escrow) {
    this.escrow = escrow;
  }


  public Balance reward(@jakarta.annotation.Nullable BigDecimal reward) {
    this.reward = reward;
    return this;
  }

  /**
   * Get reward
   * @return reward
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REWARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getReward() {
    return reward;
  }


  @JsonProperty(JSON_PROPERTY_REWARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReward(@jakarta.annotation.Nullable BigDecimal reward) {
    this.reward = reward;
  }


  public Balance session(@jakarta.annotation.Nullable String session) {
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSession() {
    return session;
  }


  @JsonProperty(JSON_PROPERTY_SESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSession(@jakarta.annotation.Nullable String session) {
    this.session = session;
  }


  public Balance total(@jakarta.annotation.Nullable BigDecimal total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(@jakarta.annotation.Nullable BigDecimal total) {
    this.total = total;
  }


  public Balance userUuid(@jakarta.annotation.Nullable String userUuid) {
    this.userUuid = userUuid;
    return this;
  }

  /**
   * Get userUuid
   * @return userUuid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUserUuid() {
    return userUuid;
  }


  @JsonProperty(JSON_PROPERTY_USER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserUuid(@jakarta.annotation.Nullable String userUuid) {
    this.userUuid = userUuid;
  }


  public Balance voucher(@jakarta.annotation.Nullable BigDecimal voucher) {
    this.voucher = voucher;
    return this;
  }

  /**
   * Get voucher
   * @return voucher
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VOUCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getVoucher() {
    return voucher;
  }


  @JsonProperty(JSON_PROPERTY_VOUCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVoucher(@jakarta.annotation.Nullable BigDecimal voucher) {
    this.voucher = voucher;
  }


  /**
   * Return true if this Balance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Balance balance = (Balance) o;
    return Objects.equals(this.algorithm, balance.algorithm) &&
        Objects.equals(this.balance, balance.balance) &&
        Objects.equals(this.ciphertext, balance.ciphertext) &&
        Objects.equals(this.escrow, balance.escrow) &&
        Objects.equals(this.reward, balance.reward) &&
        Objects.equals(this.session, balance.session) &&
        Objects.equals(this.total, balance.total) &&
        Objects.equals(this.userUuid, balance.userUuid) &&
        Objects.equals(this.voucher, balance.voucher);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithm, balance, ciphertext, escrow, reward, session, total, userUuid, voucher);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Balance {\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    ciphertext: ").append(toIndentedString(ciphertext)).append("\n");
    sb.append("    escrow: ").append(toIndentedString(escrow)).append("\n");
    sb.append("    reward: ").append(toIndentedString(reward)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    voucher: ").append(toIndentedString(voucher)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `algorithm` to the URL query string
    if (getAlgorithm() != null) {
      joiner.add(String.format("%salgorithm%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlgorithm()))));
    }

    // add `balance` to the URL query string
    if (getBalance() != null) {
      joiner.add(String.format("%sbalance%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBalance()))));
    }

    // add `ciphertext` to the URL query string
    if (getCiphertext() != null) {
      joiner.add(String.format("%sciphertext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCiphertext()))));
    }

    // add `escrow` to the URL query string
    if (getEscrow() != null) {
      joiner.add(String.format("%sescrow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEscrow()))));
    }

    // add `reward` to the URL query string
    if (getReward() != null) {
      joiner.add(String.format("%sreward%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReward()))));
    }

    // add `session` to the URL query string
    if (getSession() != null) {
      joiner.add(String.format("%ssession%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSession()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format("%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `userUuid` to the URL query string
    if (getUserUuid() != null) {
      joiner.add(String.format("%suserUuid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserUuid()))));
    }

    // add `voucher` to the URL query string
    if (getVoucher() != null) {
      joiner.add(String.format("%svoucher%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVoucher()))));
    }

    return joiner.toString();
  }
}

