/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import cloud.neice.ApiClient;
/**
 * CertificateCode
 */
@JsonPropertyOrder({
  CertificateCode.JSON_PROPERTY_CODE,
  CertificateCode.JSON_PROPERTY_DOMAIN,
  CertificateCode.JSON_PROPERTY_EXCHANGE,
  CertificateCode.JSON_PROPERTY_MODEL,
  CertificateCode.JSON_PROPERTY_QUALITY,
  CertificateCode.JSON_PROPERTY_QUERY,
  CertificateCode.JSON_PROPERTY_RESERVE,
  CertificateCode.JSON_PROPERTY_TOKEN,
  CertificateCode.JSON_PROPERTY_UDID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CertificateCode {
  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @jakarta.annotation.Nullable
  private String domain;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @jakarta.annotation.Nullable
  private OffsetDateTime exchange;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private String model;

  public static final String JSON_PROPERTY_QUALITY = "quality";
  @jakarta.annotation.Nullable
  private Integer quality;

  public static final String JSON_PROPERTY_QUERY = "query";
  @jakarta.annotation.Nullable
  private String query;

  public static final String JSON_PROPERTY_RESERVE = "reserve";
  @jakarta.annotation.Nullable
  private Boolean reserve;

  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nonnull
  private String token;

  public static final String JSON_PROPERTY_UDID = "udid";
  @jakarta.annotation.Nullable
  private String udid;

  public CertificateCode() { 
  }

  public CertificateCode code(@jakarta.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * 证书兑换码
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = code;
  }


  public CertificateCode domain(@jakarta.annotation.Nullable String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * 证书兑换系统的域名，请先在网站配置域名及其对应的API地址
   * @return domain
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(@jakarta.annotation.Nullable String domain) {
    this.domain = domain;
  }


  public CertificateCode exchange(@jakarta.annotation.Nullable OffsetDateTime exchange) {
    this.exchange = exchange;
    return this;
  }

  /**
   * 兑换码完成兑换的时间
   * @return exchange
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getExchange() {
    return exchange;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@jakarta.annotation.Nullable OffsetDateTime exchange) {
    this.exchange = exchange;
  }


  public CertificateCode model(@jakarta.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * 设备型号:iPhone,iPad,iPod
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@jakarta.annotation.Nullable String model) {
    this.model = model;
  }


  public CertificateCode quality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
    return this;
  }

  /**
   * 默认为0:不质保,最大不能超过365天，该值仅作为参考，不作为依据，具体以上游系统为准
   * @return quality
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getQuality() {
    return quality;
  }


  @JsonProperty(JSON_PROPERTY_QUALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
  }


  public CertificateCode query(@jakarta.annotation.Nullable String query) {
    this.query = query;
    return this;
  }

  /**
   * 证书查询码
   * @return query
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@jakarta.annotation.Nullable String query) {
    this.query = query;
  }


  public CertificateCode reserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
    return this;
  }

  /**
   * 表示该兑换码是否是兑换的预定证书，该值仅作为参考，不作为依据，具体以上游系统为准
   * @return reserve
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESERVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getReserve() {
    return reserve;
  }


  @JsonProperty(JSON_PROPERTY_RESERVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
  }


  public CertificateCode token(@jakarta.annotation.Nonnull String token) {
    this.token = token;
    return this;
  }

  /**
   * 请求鉴权令牌
   * @return token
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(@jakarta.annotation.Nonnull String token) {
    this.token = token;
  }


  public CertificateCode udid(@jakarta.annotation.Nullable String udid) {
    this.udid = udid;
    return this;
  }

  /**
   * 绑定设备的UDID，兑换时绑定
   * @return udid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UDID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUdid() {
    return udid;
  }


  @JsonProperty(JSON_PROPERTY_UDID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUdid(@jakarta.annotation.Nullable String udid) {
    this.udid = udid;
  }


  /**
   * Return true if this CertificateCode object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateCode certificateCode = (CertificateCode) o;
    return Objects.equals(this.code, certificateCode.code) &&
        Objects.equals(this.domain, certificateCode.domain) &&
        Objects.equals(this.exchange, certificateCode.exchange) &&
        Objects.equals(this.model, certificateCode.model) &&
        Objects.equals(this.quality, certificateCode.quality) &&
        Objects.equals(this.query, certificateCode.query) &&
        Objects.equals(this.reserve, certificateCode.reserve) &&
        Objects.equals(this.token, certificateCode.token) &&
        Objects.equals(this.udid, certificateCode.udid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, domain, exchange, model, quality, query, reserve, token, udid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateCode {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    reserve: ").append(toIndentedString(reserve)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format("%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `exchange` to the URL query string
    if (getExchange() != null) {
      joiner.add(String.format("%sexchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchange()))));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(String.format("%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
    }

    // add `quality` to the URL query string
    if (getQuality() != null) {
      joiner.add(String.format("%squality%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuality()))));
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format("%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    // add `reserve` to the URL query string
    if (getReserve() != null) {
      joiner.add(String.format("%sreserve%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReserve()))));
    }

    // add `token` to the URL query string
    if (getToken() != null) {
      joiner.add(String.format("%stoken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToken()))));
    }

    // add `udid` to the URL query string
    if (getUdid() != null) {
      joiner.add(String.format("%sudid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUdid()))));
    }

    return joiner.toString();
  }
}

