/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.neice.JSON;

/**
 * DeviceRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class DeviceRequest {
  public static final String SERIALIZED_NAME_CALLBACK = "callback";
  @SerializedName(SERIALIZED_NAME_CALLBACK)
  @jakarta.annotation.Nullable
  private String callback;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @jakarta.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @jakarta.annotation.Nullable
  private String model;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @jakarta.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PARAM = "param";
  @SerializedName(SERIALIZED_NAME_PARAM)
  @jakarta.annotation.Nullable
  private String param;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  @jakarta.annotation.Nullable
  private String phone;

  public static final String SERIALIZED_NAME_QUALITY = "quality";
  @SerializedName(SERIALIZED_NAME_QUALITY)
  @jakarta.annotation.Nullable
  private Integer quality;

  public static final String SERIALIZED_NAME_REFER = "refer";
  @SerializedName(SERIALIZED_NAME_REFER)
  @jakarta.annotation.Nullable
  private String refer;

  public static final String SERIALIZED_NAME_RENEW = "renew";
  @SerializedName(SERIALIZED_NAME_RENEW)
  @jakarta.annotation.Nullable
  private Boolean renew;

  public static final String SERIALIZED_NAME_RESERVE = "reserve";
  @SerializedName(SERIALIZED_NAME_RESERVE)
  @jakarta.annotation.Nullable
  private Boolean reserve;

  public static final String SERIALIZED_NAME_SYSTEM = "system";
  @SerializedName(SERIALIZED_NAME_SYSTEM)
  @jakarta.annotation.Nullable
  private String system;

  public static final String SERIALIZED_NAME_UDID = "udid";
  @SerializedName(SERIALIZED_NAME_UDID)
  @jakarta.annotation.Nonnull
  private String udid;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  @jakarta.annotation.Nullable
  private String uuid;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @jakarta.annotation.Nullable
  private String version;

  public DeviceRequest() {
  }

  public DeviceRequest callback(@jakarta.annotation.Nullable String callback) {
    this.callback = callback;
    return this;
  }

  /**
   * 预定证书激活时可通过回调地址将证书推送到业务系统中，为空将不会回调
   * @return callback
   */
  @jakarta.annotation.Nullable
  public String getCallback() {
    return callback;
  }

  public void setCallback(@jakarta.annotation.Nullable String callback) {
    this.callback = callback;
  }


  public DeviceRequest code(@jakarta.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * 可使用兑换码注册设备
   * @return code
   */
  @jakarta.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = code;
  }


  public DeviceRequest model(@jakarta.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * 兑换设备的手机型号，非必要参数
   * @return model
   */
  @jakarta.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@jakarta.annotation.Nullable String model) {
    this.model = model;
  }


  public DeviceRequest name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * 当调用的预定证书激活时，激活通知短信将发送该名称，方便区分，允许为空值
   * @return name
   */
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public DeviceRequest param(@jakarta.annotation.Nullable String param) {
    this.param = param;
    return this;
  }

  /**
   * 额外透传参数，非必要参数
   * @return param
   */
  @jakarta.annotation.Nullable
  public String getParam() {
    return param;
  }

  public void setParam(@jakarta.annotation.Nullable String param) {
    this.param = param;
  }


  public DeviceRequest phone(@jakarta.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * 预定手机:设备激活后发送可以安装APP的通知短信，当注册预定证书时，电话号码不能为空值
   * @return phone
   */
  @jakarta.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(@jakarta.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public DeviceRequest quality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
    return this;
  }

  /**
   * 增加质保天数后台可能会增加计费
   * @return quality
   */
  @jakarta.annotation.Nullable
  public Integer getQuality() {
    return quality;
  }

  public void setQuality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
  }


  public DeviceRequest refer(@jakarta.annotation.Nullable String refer) {
    this.refer = refer;
    return this;
  }

  /**
   * 下游系统可以标记该设备的注册用户，上游系统将透传回去，非必要参数
   * @return refer
   */
  @jakarta.annotation.Nullable
  public String getRefer() {
    return refer;
  }

  public void setRefer(@jakarta.annotation.Nullable String refer) {
    this.refer = refer;
  }


  public DeviceRequest renew(@jakarta.annotation.Nullable Boolean renew) {
    this.renew = renew;
    return this;
  }

  /**
   * 标记该设备是否是免费补签请求
   * @return renew
   */
  @jakarta.annotation.Nullable
  public Boolean getRenew() {
    return renew;
  }

  public void setRenew(@jakarta.annotation.Nullable Boolean renew) {
    this.renew = renew;
  }


  public DeviceRequest reserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
    return this;
  }

  /**
   * 证书预定参数开关如果卡设备，将在设备处于激活状态时通知用户安装
   * @return reserve
   */
  @jakarta.annotation.Nullable
  public Boolean getReserve() {
    return reserve;
  }

  public void setReserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
  }


  public DeviceRequest system(@jakarta.annotation.Nullable String system) {
    this.system = system;
    return this;
  }

  /**
   * 兑换设备的系统，非必要参数
   * @return system
   */
  @jakarta.annotation.Nullable
  public String getSystem() {
    return system;
  }

  public void setSystem(@jakarta.annotation.Nullable String system) {
    this.system = system;
  }


  public DeviceRequest udid(@jakarta.annotation.Nonnull String udid) {
    this.udid = udid;
    return this;
  }

  /**
   * iOS或iPad设备UDID
   * @return udid
   */
  @jakarta.annotation.Nonnull
  public String getUdid() {
    return udid;
  }

  public void setUdid(@jakarta.annotation.Nonnull String udid) {
    this.udid = udid;
  }


  public DeviceRequest uuid(@jakarta.annotation.Nullable String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * 免费补签时，指定需要补签证书对应的UUID
   * @return uuid
   */
  @jakarta.annotation.Nullable
  public String getUuid() {
    return uuid;
  }

  public void setUuid(@jakarta.annotation.Nullable String uuid) {
    this.uuid = uuid;
  }


  public DeviceRequest version(@jakarta.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * 兑换设备的客户端版本，非必要参数
   * @return version
   */
  @jakarta.annotation.Nullable
  public String getVersion() {
    return version;
  }

  public void setVersion(@jakarta.annotation.Nullable String version) {
    this.version = version;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceRequest deviceRequest = (DeviceRequest) o;
    return Objects.equals(this.callback, deviceRequest.callback) &&
        Objects.equals(this.code, deviceRequest.code) &&
        Objects.equals(this.model, deviceRequest.model) &&
        Objects.equals(this.name, deviceRequest.name) &&
        Objects.equals(this.param, deviceRequest.param) &&
        Objects.equals(this.phone, deviceRequest.phone) &&
        Objects.equals(this.quality, deviceRequest.quality) &&
        Objects.equals(this.refer, deviceRequest.refer) &&
        Objects.equals(this.renew, deviceRequest.renew) &&
        Objects.equals(this.reserve, deviceRequest.reserve) &&
        Objects.equals(this.system, deviceRequest.system) &&
        Objects.equals(this.udid, deviceRequest.udid) &&
        Objects.equals(this.uuid, deviceRequest.uuid) &&
        Objects.equals(this.version, deviceRequest.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callback, code, model, name, param, phone, quality, refer, renew, reserve, system, udid, uuid, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceRequest {\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    refer: ").append(toIndentedString(refer)).append("\n");
    sb.append("    renew: ").append(toIndentedString(renew)).append("\n");
    sb.append("    reserve: ").append(toIndentedString(reserve)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("callback");
    openapiFields.add("code");
    openapiFields.add("model");
    openapiFields.add("name");
    openapiFields.add("param");
    openapiFields.add("phone");
    openapiFields.add("quality");
    openapiFields.add("refer");
    openapiFields.add("renew");
    openapiFields.add("reserve");
    openapiFields.add("system");
    openapiFields.add("udid");
    openapiFields.add("uuid");
    openapiFields.add("version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("udid");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeviceRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeviceRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeviceRequest is not found in the empty JSON string", DeviceRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeviceRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeviceRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeviceRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("callback") != null && !jsonObj.get("callback").isJsonNull()) && !jsonObj.get("callback").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `callback` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callback").toString()));
      }
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("param") != null && !jsonObj.get("param").isJsonNull()) && !jsonObj.get("param").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `param` to be a primitive type in the JSON string but got `%s`", jsonObj.get("param").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if ((jsonObj.get("refer") != null && !jsonObj.get("refer").isJsonNull()) && !jsonObj.get("refer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refer").toString()));
      }
      if ((jsonObj.get("system") != null && !jsonObj.get("system").isJsonNull()) && !jsonObj.get("system").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `system` to be a primitive type in the JSON string but got `%s`", jsonObj.get("system").toString()));
      }
      if (!jsonObj.get("udid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `udid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("udid").toString()));
      }
      if ((jsonObj.get("uuid") != null && !jsonObj.get("uuid").isJsonNull()) && !jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
      if ((jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) && !jsonObj.get("version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeviceRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeviceRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeviceRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeviceRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeviceRequest>() {
           @Override
           public void write(JsonWriter out, DeviceRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeviceRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeviceRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeviceRequest
   * @throws IOException if the JSON string is invalid with respect to DeviceRequest
   */
  public static DeviceRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeviceRequest.class);
  }

  /**
   * Convert an instance of DeviceRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

