/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * OpenEnterpriseCertificate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-30T12:28:02.341031+08:00[Asia/Shanghai]")
public class OpenEnterpriseCertificate {
  public static final String SERIALIZED_NAME_CERTIFICATE = "certificate";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE)
  private String certificate;

  public static final String SERIALIZED_NAME_CERTIFICATE_NAME = "certificateName";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_NAME)
  private String certificateName;

  public static final String SERIALIZED_NAME_CREATE_TIME = "createTime";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  private OffsetDateTime createTime;

  public static final String SERIALIZED_NAME_ISSUER_DN = "issuerDn";
  @SerializedName(SERIALIZED_NAME_ISSUER_DN)
  private String issuerDn;

  public static final String SERIALIZED_NAME_MD5 = "md5";
  @SerializedName(SERIALIZED_NAME_MD5)
  private String md5;

  public static final String SERIALIZED_NAME_MOBILEPROVISION = "mobileprovision";
  @SerializedName(SERIALIZED_NAME_MOBILEPROVISION)
  private String mobileprovision;

  public static final String SERIALIZED_NAME_NOT_AFTER = "notAfter";
  @SerializedName(SERIALIZED_NAME_NOT_AFTER)
  private OffsetDateTime notAfter;

  public static final String SERIALIZED_NAME_NOT_BEFORE = "notBefore";
  @SerializedName(SERIALIZED_NAME_NOT_BEFORE)
  private OffsetDateTime notBefore;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_REVOCATION_REASON = "revocationReason";
  @SerializedName(SERIALIZED_NAME_REVOCATION_REASON)
  private String revocationReason;

  public static final String SERIALIZED_NAME_REVOCATION_TIME = "revocationTime";
  @SerializedName(SERIALIZED_NAME_REVOCATION_TIME)
  private OffsetDateTime revocationTime;

  public static final String SERIALIZED_NAME_SERIAL_NUMBER = "serialNumber";
  @SerializedName(SERIALIZED_NAME_SERIAL_NUMBER)
  private String serialNumber;

  public static final String SERIALIZED_NAME_SUBJECT_DN = "subjectDn";
  @SerializedName(SERIALIZED_NAME_SUBJECT_DN)
  private String subjectDn;

  public static final String SERIALIZED_NAME_TEAM_ID = "teamId";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  private String teamId;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_VALID = "valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  private Boolean valid;


  public OpenEnterpriseCertificate certificate(String certificate) {
    
    this.certificate = certificate;
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCertificate() {
    return certificate;
  }


  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }


  public OpenEnterpriseCertificate certificateName(String certificateName) {
    
    this.certificateName = certificateName;
    return this;
  }

   /**
   * Get certificateName
   * @return certificateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCertificateName() {
    return certificateName;
  }


  public void setCertificateName(String certificateName) {
    this.certificateName = certificateName;
  }


  public OpenEnterpriseCertificate createTime(OffsetDateTime createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreateTime() {
    return createTime;
  }


  public void setCreateTime(OffsetDateTime createTime) {
    this.createTime = createTime;
  }


  public OpenEnterpriseCertificate issuerDn(String issuerDn) {
    
    this.issuerDn = issuerDn;
    return this;
  }

   /**
   * Get issuerDn
   * @return issuerDn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIssuerDn() {
    return issuerDn;
  }


  public void setIssuerDn(String issuerDn) {
    this.issuerDn = issuerDn;
  }


  public OpenEnterpriseCertificate md5(String md5) {
    
    this.md5 = md5;
    return this;
  }

   /**
   * Get md5
   * @return md5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMd5() {
    return md5;
  }


  public void setMd5(String md5) {
    this.md5 = md5;
  }


  public OpenEnterpriseCertificate mobileprovision(String mobileprovision) {
    
    this.mobileprovision = mobileprovision;
    return this;
  }

   /**
   * Get mobileprovision
   * @return mobileprovision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMobileprovision() {
    return mobileprovision;
  }


  public void setMobileprovision(String mobileprovision) {
    this.mobileprovision = mobileprovision;
  }


  public OpenEnterpriseCertificate notAfter(OffsetDateTime notAfter) {
    
    this.notAfter = notAfter;
    return this;
  }

   /**
   * Get notAfter
   * @return notAfter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getNotAfter() {
    return notAfter;
  }


  public void setNotAfter(OffsetDateTime notAfter) {
    this.notAfter = notAfter;
  }


  public OpenEnterpriseCertificate notBefore(OffsetDateTime notBefore) {
    
    this.notBefore = notBefore;
    return this;
  }

   /**
   * Get notBefore
   * @return notBefore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getNotBefore() {
    return notBefore;
  }


  public void setNotBefore(OffsetDateTime notBefore) {
    this.notBefore = notBefore;
  }


  public OpenEnterpriseCertificate password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public OpenEnterpriseCertificate revocationReason(String revocationReason) {
    
    this.revocationReason = revocationReason;
    return this;
  }

   /**
   * Get revocationReason
   * @return revocationReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRevocationReason() {
    return revocationReason;
  }


  public void setRevocationReason(String revocationReason) {
    this.revocationReason = revocationReason;
  }


  public OpenEnterpriseCertificate revocationTime(OffsetDateTime revocationTime) {
    
    this.revocationTime = revocationTime;
    return this;
  }

   /**
   * Get revocationTime
   * @return revocationTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getRevocationTime() {
    return revocationTime;
  }


  public void setRevocationTime(OffsetDateTime revocationTime) {
    this.revocationTime = revocationTime;
  }


  public OpenEnterpriseCertificate serialNumber(String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSerialNumber() {
    return serialNumber;
  }


  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  public OpenEnterpriseCertificate subjectDn(String subjectDn) {
    
    this.subjectDn = subjectDn;
    return this;
  }

   /**
   * Get subjectDn
   * @return subjectDn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubjectDn() {
    return subjectDn;
  }


  public void setSubjectDn(String subjectDn) {
    this.subjectDn = subjectDn;
  }


  public OpenEnterpriseCertificate teamId(String teamId) {
    
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTeamId() {
    return teamId;
  }


  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }


  public OpenEnterpriseCertificate uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public OpenEnterpriseCertificate valid(Boolean valid) {
    
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getValid() {
    return valid;
  }


  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenEnterpriseCertificate openEnterpriseCertificate = (OpenEnterpriseCertificate) o;
    return Objects.equals(this.certificate, openEnterpriseCertificate.certificate) &&
        Objects.equals(this.certificateName, openEnterpriseCertificate.certificateName) &&
        Objects.equals(this.createTime, openEnterpriseCertificate.createTime) &&
        Objects.equals(this.issuerDn, openEnterpriseCertificate.issuerDn) &&
        Objects.equals(this.md5, openEnterpriseCertificate.md5) &&
        Objects.equals(this.mobileprovision, openEnterpriseCertificate.mobileprovision) &&
        Objects.equals(this.notAfter, openEnterpriseCertificate.notAfter) &&
        Objects.equals(this.notBefore, openEnterpriseCertificate.notBefore) &&
        Objects.equals(this.password, openEnterpriseCertificate.password) &&
        Objects.equals(this.revocationReason, openEnterpriseCertificate.revocationReason) &&
        Objects.equals(this.revocationTime, openEnterpriseCertificate.revocationTime) &&
        Objects.equals(this.serialNumber, openEnterpriseCertificate.serialNumber) &&
        Objects.equals(this.subjectDn, openEnterpriseCertificate.subjectDn) &&
        Objects.equals(this.teamId, openEnterpriseCertificate.teamId) &&
        Objects.equals(this.uuid, openEnterpriseCertificate.uuid) &&
        Objects.equals(this.valid, openEnterpriseCertificate.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificate, certificateName, createTime, issuerDn, md5, mobileprovision, notAfter, notBefore, password, revocationReason, revocationTime, serialNumber, subjectDn, teamId, uuid, valid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenEnterpriseCertificate {\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certificateName: ").append(toIndentedString(certificateName)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    issuerDn: ").append(toIndentedString(issuerDn)).append("\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    mobileprovision: ").append(toIndentedString(mobileprovision)).append("\n");
    sb.append("    notAfter: ").append(toIndentedString(notAfter)).append("\n");
    sb.append("    notBefore: ").append(toIndentedString(notBefore)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    revocationReason: ").append(toIndentedString(revocationReason)).append("\n");
    sb.append("    revocationTime: ").append(toIndentedString(revocationTime)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    subjectDn: ").append(toIndentedString(subjectDn)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

