/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import cloud.neice.ApiClient;
/**
 * PersonalCertificate
 */
@JsonPropertyOrder({
  PersonalCertificate.JSON_PROPERTY_CERTIFICATE,
  PersonalCertificate.JSON_PROPERTY_CERTIFICATE_ID,
  PersonalCertificate.JSON_PROPERTY_CODE,
  PersonalCertificate.JSON_PROPERTY_CREATE_TIME,
  PersonalCertificate.JSON_PROPERTY_DESCRIPTION,
  PersonalCertificate.JSON_PROPERTY_DEVICE_ID,
  PersonalCertificate.JSON_PROPERTY_EXPERIENCE,
  PersonalCertificate.JSON_PROPERTY_INVISIBLE,
  PersonalCertificate.JSON_PROPERTY_LOCK,
  PersonalCertificate.JSON_PROPERTY_MOBILEPROVISION,
  PersonalCertificate.JSON_PROPERTY_NAME,
  PersonalCertificate.JSON_PROPERTY_PASSWORD,
  PersonalCertificate.JSON_PROPERTY_PHONE,
  PersonalCertificate.JSON_PROPERTY_PRICE,
  PersonalCertificate.JSON_PROPERTY_PROFILE,
  PersonalCertificate.JSON_PROPERTY_PROFILE_ID,
  PersonalCertificate.JSON_PROPERTY_QUALITY,
  PersonalCertificate.JSON_PROPERTY_QUALITY_TIME,
  PersonalCertificate.JSON_PROPERTY_REFER,
  PersonalCertificate.JSON_PROPERTY_REPAIR,
  PersonalCertificate.JSON_PROPERTY_RESERVE,
  PersonalCertificate.JSON_PROPERTY_SERIAL_NUMBER,
  PersonalCertificate.JSON_PROPERTY_TAG,
  PersonalCertificate.JSON_PROPERTY_TEAM,
  PersonalCertificate.JSON_PROPERTY_TEAM_ID,
  PersonalCertificate.JSON_PROPERTY_UDID,
  PersonalCertificate.JSON_PROPERTY_UUID,
  PersonalCertificate.JSON_PROPERTY_VALID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PersonalCertificate {
  public static final String JSON_PROPERTY_CERTIFICATE = "certificate";
  @jakarta.annotation.Nullable
  private String certificate;

  public static final String JSON_PROPERTY_CERTIFICATE_ID = "certificateId";
  @jakarta.annotation.Nullable
  private String certificateId;

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  @jakarta.annotation.Nullable
  private String createTime;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_DEVICE_ID = "deviceId";
  @jakarta.annotation.Nullable
  private String deviceId;

  public static final String JSON_PROPERTY_EXPERIENCE = "experience";
  @jakarta.annotation.Nullable
  private Integer experience;

  public static final String JSON_PROPERTY_INVISIBLE = "invisible";
  @jakarta.annotation.Nullable
  private Boolean invisible;

  public static final String JSON_PROPERTY_LOCK = "lock";
  @jakarta.annotation.Nullable
  private Integer lock;

  public static final String JSON_PROPERTY_MOBILEPROVISION = "mobileprovision";
  @jakarta.annotation.Nullable
  private String mobileprovision;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @jakarta.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  @jakarta.annotation.Nullable
  private String profile;

  public static final String JSON_PROPERTY_PROFILE_ID = "profileId";
  @jakarta.annotation.Nullable
  private String profileId;

  public static final String JSON_PROPERTY_QUALITY = "quality";
  @jakarta.annotation.Nullable
  private Integer quality;

  public static final String JSON_PROPERTY_QUALITY_TIME = "qualityTime";
  @jakarta.annotation.Nullable
  private String qualityTime;

  public static final String JSON_PROPERTY_REFER = "refer";
  @jakarta.annotation.Nullable
  private String refer;

  public static final String JSON_PROPERTY_REPAIR = "repair";
  @jakarta.annotation.Nullable
  private Boolean repair;

  public static final String JSON_PROPERTY_RESERVE = "reserve";
  @jakarta.annotation.Nullable
  private Boolean reserve;

  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  @jakarta.annotation.Nullable
  private String serialNumber;

  public static final String JSON_PROPERTY_TAG = "tag";
  @jakarta.annotation.Nullable
  private String tag;

  public static final String JSON_PROPERTY_TEAM = "team";
  @jakarta.annotation.Nullable
  private String team;

  public static final String JSON_PROPERTY_TEAM_ID = "teamId";
  @jakarta.annotation.Nullable
  private String teamId;

  public static final String JSON_PROPERTY_UDID = "udid";
  @jakarta.annotation.Nullable
  private String udid;

  public static final String JSON_PROPERTY_UUID = "uuid";
  @jakarta.annotation.Nullable
  private String uuid;

  public static final String JSON_PROPERTY_VALID = "valid";
  @jakarta.annotation.Nullable
  private Boolean valid;

  public PersonalCertificate() { 
  }

  public PersonalCertificate certificate(@jakarta.annotation.Nullable String certificate) {
    this.certificate = certificate;
    return this;
  }

  /**
   * 设备证书P12
   * @return certificate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCertificate() {
    return certificate;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificate(@jakarta.annotation.Nullable String certificate) {
    this.certificate = certificate;
  }


  public PersonalCertificate certificateId(@jakarta.annotation.Nullable String certificateId) {
    this.certificateId = certificateId;
    return this;
  }

  /**
   * 证书ID
   * @return certificateId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCertificateId() {
    return certificateId;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateId(@jakarta.annotation.Nullable String certificateId) {
    this.certificateId = certificateId;
  }


  public PersonalCertificate code(@jakarta.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * 证书兑换码
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = code;
  }


  public PersonalCertificate createTime(@jakarta.annotation.Nullable String createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * 证书创建时间
   * @return createTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreateTime() {
    return createTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateTime(@jakarta.annotation.Nullable String createTime) {
    this.createTime = createTime;
  }


  public PersonalCertificate description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * 证书描述信息
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public PersonalCertificate deviceId(@jakarta.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * 设备ID
   * @return deviceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeviceId() {
    return deviceId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceId(@jakarta.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
  }


  public PersonalCertificate experience(@jakarta.annotation.Nullable Integer experience) {
    this.experience = experience;
    return this;
  }

  /**
   * 允许用户体验的次数
   * @return experience
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPERIENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExperience() {
    return experience;
  }


  @JsonProperty(JSON_PROPERTY_EXPERIENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExperience(@jakarta.annotation.Nullable Integer experience) {
    this.experience = experience;
  }


  public PersonalCertificate invisible(@jakarta.annotation.Nullable Boolean invisible) {
    this.invisible = invisible;
    return this;
  }

  /**
   * 隐形证书
   * @return invisible
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVISIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getInvisible() {
    return invisible;
  }


  @JsonProperty(JSON_PROPERTY_INVISIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvisible(@jakarta.annotation.Nullable Boolean invisible) {
    this.invisible = invisible;
  }


  public PersonalCertificate lock(@jakarta.annotation.Nullable Integer lock) {
    this.lock = lock;
    return this;
  }

  /**
   * 锁定:0,不加锁;100,导出锁;200,体验锁;300,解码锁;400,付款锁;500,优惠锁;600,包月锁;700,续费锁;800,备份锁;10000,杀死锁
   * @return lock
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLock() {
    return lock;
  }


  @JsonProperty(JSON_PROPERTY_LOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLock(@jakarta.annotation.Nullable Integer lock) {
    this.lock = lock;
  }


  public PersonalCertificate mobileprovision(@jakarta.annotation.Nullable String mobileprovision) {
    this.mobileprovision = mobileprovision;
    return this;
  }

  /**
   * 设备的描述文件Mobileprovision
   * @return mobileprovision
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOBILEPROVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMobileprovision() {
    return mobileprovision;
  }


  @JsonProperty(JSON_PROPERTY_MOBILEPROVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMobileprovision(@jakarta.annotation.Nullable String mobileprovision) {
    this.mobileprovision = mobileprovision;
  }


  public PersonalCertificate name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * 证书名称
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public PersonalCertificate password(@jakarta.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * 设备证书密码
   * @return password
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@jakarta.annotation.Nullable String password) {
    this.password = password;
  }


  public PersonalCertificate phone(@jakarta.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * 预定手机
   * @return phone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@jakarta.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public PersonalCertificate price(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * 服务价格
   * @return price
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public PersonalCertificate profile(@jakarta.annotation.Nullable String profile) {
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(@jakarta.annotation.Nullable String profile) {
    this.profile = profile;
  }


  public PersonalCertificate profileId(@jakarta.annotation.Nullable String profileId) {
    this.profileId = profileId;
    return this;
  }

  /**
   * 描述文件ID
   * @return profileId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProfileId() {
    return profileId;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileId(@jakarta.annotation.Nullable String profileId) {
    this.profileId = profileId;
  }


  public PersonalCertificate quality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
    return this;
  }

  /**
   * 证书质保天数
   * @return quality
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getQuality() {
    return quality;
  }


  @JsonProperty(JSON_PROPERTY_QUALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
  }


  public PersonalCertificate qualityTime(@jakarta.annotation.Nullable String qualityTime) {
    this.qualityTime = qualityTime;
    return this;
  }

  /**
   * 证书质保到期时间
   * @return qualityTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUALITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQualityTime() {
    return qualityTime;
  }


  @JsonProperty(JSON_PROPERTY_QUALITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualityTime(@jakarta.annotation.Nullable String qualityTime) {
    this.qualityTime = qualityTime;
  }


  public PersonalCertificate refer(@jakarta.annotation.Nullable String refer) {
    this.refer = refer;
    return this;
  }

  /**
   * 该设备的用户,后台自动透传该参数
   * @return refer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRefer() {
    return refer;
  }


  @JsonProperty(JSON_PROPERTY_REFER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefer(@jakarta.annotation.Nullable String refer) {
    this.refer = refer;
  }


  public PersonalCertificate repair(@jakarta.annotation.Nullable Boolean repair) {
    this.repair = repair;
    return this;
  }

  /**
   * 补偿证书:预定失败或质保期内掉签，后台重订的设备标记，一般免服务费
   * @return repair
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPAIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRepair() {
    return repair;
  }


  @JsonProperty(JSON_PROPERTY_REPAIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepair(@jakarta.annotation.Nullable Boolean repair) {
    this.repair = repair;
  }


  public PersonalCertificate reserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
    return this;
  }

  /**
   * 预定证书
   * @return reserve
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESERVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getReserve() {
    return reserve;
  }


  @JsonProperty(JSON_PROPERTY_RESERVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
  }


  public PersonalCertificate serialNumber(@jakarta.annotation.Nullable String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

  /**
   * Get serialNumber
   * @return serialNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerialNumber(@jakarta.annotation.Nullable String serialNumber) {
    this.serialNumber = serialNumber;
  }


  public PersonalCertificate tag(@jakarta.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTag() {
    return tag;
  }


  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(@jakarta.annotation.Nullable String tag) {
    this.tag = tag;
  }


  public PersonalCertificate team(@jakarta.annotation.Nullable String team) {
    this.team = team;
    return this;
  }

  /**
   * Get team
   * @return team
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTeam() {
    return team;
  }


  @JsonProperty(JSON_PROPERTY_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeam(@jakarta.annotation.Nullable String team) {
    this.team = team;
  }


  public PersonalCertificate teamId(@jakarta.annotation.Nullable String teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * Get teamId
   * @return teamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTeamId() {
    return teamId;
  }


  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeamId(@jakarta.annotation.Nullable String teamId) {
    this.teamId = teamId;
  }


  public PersonalCertificate udid(@jakarta.annotation.Nullable String udid) {
    this.udid = udid;
    return this;
  }

  /**
   * 设备的UDID
   * @return udid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UDID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUdid() {
    return udid;
  }


  @JsonProperty(JSON_PROPERTY_UDID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUdid(@jakarta.annotation.Nullable String udid) {
    this.udid = udid;
  }


  public PersonalCertificate uuid(@jakarta.annotation.Nullable String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * 单个设备证书UUID
   * @return uuid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(@jakarta.annotation.Nullable String uuid) {
    this.uuid = uuid;
  }


  public PersonalCertificate valid(@jakarta.annotation.Nullable Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * 证书是否有效
   * @return valid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getValid() {
    return valid;
  }


  @JsonProperty(JSON_PROPERTY_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValid(@jakarta.annotation.Nullable Boolean valid) {
    this.valid = valid;
  }


  /**
   * Return true if this PersonalCertificate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonalCertificate personalCertificate = (PersonalCertificate) o;
    return Objects.equals(this.certificate, personalCertificate.certificate) &&
        Objects.equals(this.certificateId, personalCertificate.certificateId) &&
        Objects.equals(this.code, personalCertificate.code) &&
        Objects.equals(this.createTime, personalCertificate.createTime) &&
        Objects.equals(this.description, personalCertificate.description) &&
        Objects.equals(this.deviceId, personalCertificate.deviceId) &&
        Objects.equals(this.experience, personalCertificate.experience) &&
        Objects.equals(this.invisible, personalCertificate.invisible) &&
        Objects.equals(this.lock, personalCertificate.lock) &&
        Objects.equals(this.mobileprovision, personalCertificate.mobileprovision) &&
        Objects.equals(this.name, personalCertificate.name) &&
        Objects.equals(this.password, personalCertificate.password) &&
        Objects.equals(this.phone, personalCertificate.phone) &&
        Objects.equals(this.price, personalCertificate.price) &&
        Objects.equals(this.profile, personalCertificate.profile) &&
        Objects.equals(this.profileId, personalCertificate.profileId) &&
        Objects.equals(this.quality, personalCertificate.quality) &&
        Objects.equals(this.qualityTime, personalCertificate.qualityTime) &&
        Objects.equals(this.refer, personalCertificate.refer) &&
        Objects.equals(this.repair, personalCertificate.repair) &&
        Objects.equals(this.reserve, personalCertificate.reserve) &&
        Objects.equals(this.serialNumber, personalCertificate.serialNumber) &&
        Objects.equals(this.tag, personalCertificate.tag) &&
        Objects.equals(this.team, personalCertificate.team) &&
        Objects.equals(this.teamId, personalCertificate.teamId) &&
        Objects.equals(this.udid, personalCertificate.udid) &&
        Objects.equals(this.uuid, personalCertificate.uuid) &&
        Objects.equals(this.valid, personalCertificate.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificate, certificateId, code, createTime, description, deviceId, experience, invisible, lock, mobileprovision, name, password, phone, price, profile, profileId, quality, qualityTime, refer, repair, reserve, serialNumber, tag, team, teamId, udid, uuid, valid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonalCertificate {\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certificateId: ").append(toIndentedString(certificateId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    experience: ").append(toIndentedString(experience)).append("\n");
    sb.append("    invisible: ").append(toIndentedString(invisible)).append("\n");
    sb.append("    lock: ").append(toIndentedString(lock)).append("\n");
    sb.append("    mobileprovision: ").append(toIndentedString(mobileprovision)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    qualityTime: ").append(toIndentedString(qualityTime)).append("\n");
    sb.append("    refer: ").append(toIndentedString(refer)).append("\n");
    sb.append("    repair: ").append(toIndentedString(repair)).append("\n");
    sb.append("    reserve: ").append(toIndentedString(reserve)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `certificate` to the URL query string
    if (getCertificate() != null) {
      joiner.add(String.format("%scertificate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCertificate()))));
    }

    // add `certificateId` to the URL query string
    if (getCertificateId() != null) {
      joiner.add(String.format("%scertificateId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCertificateId()))));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `createTime` to the URL query string
    if (getCreateTime() != null) {
      joiner.add(String.format("%screateTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreateTime()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `deviceId` to the URL query string
    if (getDeviceId() != null) {
      joiner.add(String.format("%sdeviceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceId()))));
    }

    // add `experience` to the URL query string
    if (getExperience() != null) {
      joiner.add(String.format("%sexperience%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExperience()))));
    }

    // add `invisible` to the URL query string
    if (getInvisible() != null) {
      joiner.add(String.format("%sinvisible%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInvisible()))));
    }

    // add `lock` to the URL query string
    if (getLock() != null) {
      joiner.add(String.format("%slock%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLock()))));
    }

    // add `mobileprovision` to the URL query string
    if (getMobileprovision() != null) {
      joiner.add(String.format("%smobileprovision%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMobileprovision()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `password` to the URL query string
    if (getPassword() != null) {
      joiner.add(String.format("%spassword%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPassword()))));
    }

    // add `phone` to the URL query string
    if (getPhone() != null) {
      joiner.add(String.format("%sphone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhone()))));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format("%sprice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrice()))));
    }

    // add `profile` to the URL query string
    if (getProfile() != null) {
      joiner.add(String.format("%sprofile%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfile()))));
    }

    // add `profileId` to the URL query string
    if (getProfileId() != null) {
      joiner.add(String.format("%sprofileId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfileId()))));
    }

    // add `quality` to the URL query string
    if (getQuality() != null) {
      joiner.add(String.format("%squality%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuality()))));
    }

    // add `qualityTime` to the URL query string
    if (getQualityTime() != null) {
      joiner.add(String.format("%squalityTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQualityTime()))));
    }

    // add `refer` to the URL query string
    if (getRefer() != null) {
      joiner.add(String.format("%srefer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRefer()))));
    }

    // add `repair` to the URL query string
    if (getRepair() != null) {
      joiner.add(String.format("%srepair%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRepair()))));
    }

    // add `reserve` to the URL query string
    if (getReserve() != null) {
      joiner.add(String.format("%sreserve%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReserve()))));
    }

    // add `serialNumber` to the URL query string
    if (getSerialNumber() != null) {
      joiner.add(String.format("%sserialNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSerialNumber()))));
    }

    // add `tag` to the URL query string
    if (getTag() != null) {
      joiner.add(String.format("%stag%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTag()))));
    }

    // add `team` to the URL query string
    if (getTeam() != null) {
      joiner.add(String.format("%steam%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTeam()))));
    }

    // add `teamId` to the URL query string
    if (getTeamId() != null) {
      joiner.add(String.format("%steamId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTeamId()))));
    }

    // add `udid` to the URL query string
    if (getUdid() != null) {
      joiner.add(String.format("%sudid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUdid()))));
    }

    // add `uuid` to the URL query string
    if (getUuid() != null) {
      joiner.add(String.format("%suuid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUuid()))));
    }

    // add `valid` to the URL query string
    if (getValid() != null) {
      joiner.add(String.format("%svalid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValid()))));
    }

    return joiner.toString();
  }
}

