/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PersonalCertificate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-14T22:42:54.556275+08:00[Asia/Shanghai]")
public class PersonalCertificate {
  public static final String SERIALIZED_NAME_CERTIFICATE = "certificate";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE)
  private String certificate;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_MOBILEPROVISION = "mobileprovision";
  @SerializedName(SERIALIZED_NAME_MOBILEPROVISION)
  private String mobileprovision;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_UDID = "udid";
  @SerializedName(SERIALIZED_NAME_UDID)
  private String udid;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_VALID = "valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  private Boolean valid;


  public PersonalCertificate certificate(String certificate) {
    
    this.certificate = certificate;
    return this;
  }

   /**
   * 设备证书P12
   * @return certificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "设备证书P12")

  public String getCertificate() {
    return certificate;
  }


  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }


  public PersonalCertificate description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * 证书描述信息
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "证书描述信息")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PersonalCertificate mobileprovision(String mobileprovision) {
    
    this.mobileprovision = mobileprovision;
    return this;
  }

   /**
   * 设备的描述文件Mobileprovision
   * @return mobileprovision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "设备的描述文件Mobileprovision")

  public String getMobileprovision() {
    return mobileprovision;
  }


  public void setMobileprovision(String mobileprovision) {
    this.mobileprovision = mobileprovision;
  }


  public PersonalCertificate password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * 设备证书密码
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "设备证书密码")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public PersonalCertificate udid(String udid) {
    
    this.udid = udid;
    return this;
  }

   /**
   * 设备的UDID
   * @return udid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "设备的UDID")

  public String getUdid() {
    return udid;
  }


  public void setUdid(String udid) {
    this.udid = udid;
  }


  public PersonalCertificate uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * 单个设备证书UUID
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单个设备证书UUID")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public PersonalCertificate valid(Boolean valid) {
    
    this.valid = valid;
    return this;
  }

   /**
   * 证书是否有效
   * @return valid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "证书是否有效")

  public Boolean getValid() {
    return valid;
  }


  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonalCertificate personalCertificate = (PersonalCertificate) o;
    return Objects.equals(this.certificate, personalCertificate.certificate) &&
        Objects.equals(this.description, personalCertificate.description) &&
        Objects.equals(this.mobileprovision, personalCertificate.mobileprovision) &&
        Objects.equals(this.password, personalCertificate.password) &&
        Objects.equals(this.udid, personalCertificate.udid) &&
        Objects.equals(this.uuid, personalCertificate.uuid) &&
        Objects.equals(this.valid, personalCertificate.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificate, description, mobileprovision, password, udid, uuid, valid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonalCertificate {\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mobileprovision: ").append(toIndentedString(mobileprovision)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

