/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Renewable
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-15T17:38:51.789649+08:00[Asia/Shanghai]")
public class Renewable {
  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  private String domain;

  public static final String SERIALIZED_NAME_GUIDE = "guide";
  @SerializedName(SERIALIZED_NAME_GUIDE)
  private String guide;

  public static final String SERIALIZED_NAME_RENEWABLE = "renewable";
  @SerializedName(SERIALIZED_NAME_RENEWABLE)
  private Boolean renewable;

  public static final String SERIALIZED_NAME_UDID = "udid";
  @SerializedName(SERIALIZED_NAME_UDID)
  private String udid;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;


  public Renewable domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDomain() {
    return domain;
  }


  public void setDomain(String domain) {
    this.domain = domain;
  }


  public Renewable guide(String guide) {
    
    this.guide = guide;
    return this;
  }

   /**
   * Get guide
   * @return guide
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGuide() {
    return guide;
  }


  public void setGuide(String guide) {
    this.guide = guide;
  }


  public Renewable renewable(Boolean renewable) {
    
    this.renewable = renewable;
    return this;
  }

   /**
   * Get renewable
   * @return renewable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRenewable() {
    return renewable;
  }


  public void setRenewable(Boolean renewable) {
    this.renewable = renewable;
  }


  public Renewable udid(String udid) {
    
    this.udid = udid;
    return this;
  }

   /**
   * Get udid
   * @return udid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdid() {
    return udid;
  }


  public void setUdid(String udid) {
    this.udid = udid;
  }


  public Renewable url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Renewable uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Renewable renewable = (Renewable) o;
    return Objects.equals(this.domain, renewable.domain) &&
        Objects.equals(this.guide, renewable.guide) &&
        Objects.equals(this.renewable, renewable.renewable) &&
        Objects.equals(this.udid, renewable.udid) &&
        Objects.equals(this.url, renewable.url) &&
        Objects.equals(this.uuid, renewable.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, guide, renewable, udid, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Renewable {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    guide: ").append(toIndentedString(guide)).append("\n");
    sb.append("    renewable: ").append(toIndentedString(renewable)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

