/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.neice.JSON;

/**
 * Renewable
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Renewable {
  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  @jakarta.annotation.Nullable
  private String domain;

  public static final String SERIALIZED_NAME_GUIDE = "guide";
  @SerializedName(SERIALIZED_NAME_GUIDE)
  @jakarta.annotation.Nullable
  private String guide;

  public static final String SERIALIZED_NAME_RENEWABLE = "renewable";
  @SerializedName(SERIALIZED_NAME_RENEWABLE)
  @jakarta.annotation.Nullable
  private Boolean renewable;

  public static final String SERIALIZED_NAME_TEAM_ID = "teamId";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  @jakarta.annotation.Nullable
  private String teamId;

  public static final String SERIALIZED_NAME_UDID = "udid";
  @SerializedName(SERIALIZED_NAME_UDID)
  @jakarta.annotation.Nullable
  private String udid;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @jakarta.annotation.Nullable
  private String url;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  @jakarta.annotation.Nullable
  private String uuid;

  public Renewable() {
  }

  public Renewable domain(@jakarta.annotation.Nullable String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @jakarta.annotation.Nullable
  public String getDomain() {
    return domain;
  }

  public void setDomain(@jakarta.annotation.Nullable String domain) {
    this.domain = domain;
  }


  public Renewable guide(@jakarta.annotation.Nullable String guide) {
    this.guide = guide;
    return this;
  }

  /**
   * Get guide
   * @return guide
   */
  @jakarta.annotation.Nullable
  public String getGuide() {
    return guide;
  }

  public void setGuide(@jakarta.annotation.Nullable String guide) {
    this.guide = guide;
  }


  public Renewable renewable(@jakarta.annotation.Nullable Boolean renewable) {
    this.renewable = renewable;
    return this;
  }

  /**
   * Get renewable
   * @return renewable
   */
  @jakarta.annotation.Nullable
  public Boolean getRenewable() {
    return renewable;
  }

  public void setRenewable(@jakarta.annotation.Nullable Boolean renewable) {
    this.renewable = renewable;
  }


  public Renewable teamId(@jakarta.annotation.Nullable String teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * Get teamId
   * @return teamId
   */
  @jakarta.annotation.Nullable
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(@jakarta.annotation.Nullable String teamId) {
    this.teamId = teamId;
  }


  public Renewable udid(@jakarta.annotation.Nullable String udid) {
    this.udid = udid;
    return this;
  }

  /**
   * Get udid
   * @return udid
   */
  @jakarta.annotation.Nullable
  public String getUdid() {
    return udid;
  }

  public void setUdid(@jakarta.annotation.Nullable String udid) {
    this.udid = udid;
  }


  public Renewable url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  public Renewable uuid(@jakarta.annotation.Nullable String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Get uuid
   * @return uuid
   */
  @jakarta.annotation.Nullable
  public String getUuid() {
    return uuid;
  }

  public void setUuid(@jakarta.annotation.Nullable String uuid) {
    this.uuid = uuid;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Renewable renewable = (Renewable) o;
    return Objects.equals(this.domain, renewable.domain) &&
        Objects.equals(this.guide, renewable.guide) &&
        Objects.equals(this.renewable, renewable.renewable) &&
        Objects.equals(this.teamId, renewable.teamId) &&
        Objects.equals(this.udid, renewable.udid) &&
        Objects.equals(this.url, renewable.url) &&
        Objects.equals(this.uuid, renewable.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, guide, renewable, teamId, udid, url, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Renewable {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    guide: ").append(toIndentedString(guide)).append("\n");
    sb.append("    renewable: ").append(toIndentedString(renewable)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("domain");
    openapiFields.add("guide");
    openapiFields.add("renewable");
    openapiFields.add("teamId");
    openapiFields.add("udid");
    openapiFields.add("url");
    openapiFields.add("uuid");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Renewable
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Renewable.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Renewable is not found in the empty JSON string", Renewable.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Renewable.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Renewable` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("domain") != null && !jsonObj.get("domain").isJsonNull()) && !jsonObj.get("domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domain").toString()));
      }
      if ((jsonObj.get("guide") != null && !jsonObj.get("guide").isJsonNull()) && !jsonObj.get("guide").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `guide` to be a primitive type in the JSON string but got `%s`", jsonObj.get("guide").toString()));
      }
      if ((jsonObj.get("teamId") != null && !jsonObj.get("teamId").isJsonNull()) && !jsonObj.get("teamId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `teamId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("teamId").toString()));
      }
      if ((jsonObj.get("udid") != null && !jsonObj.get("udid").isJsonNull()) && !jsonObj.get("udid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `udid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("udid").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("uuid") != null && !jsonObj.get("uuid").isJsonNull()) && !jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Renewable.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Renewable' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Renewable> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Renewable.class));

       return (TypeAdapter<T>) new TypeAdapter<Renewable>() {
           @Override
           public void write(JsonWriter out, Renewable value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Renewable read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Renewable given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Renewable
   * @throws IOException if the JSON string is invalid with respect to Renewable
   */
  public static Renewable fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Renewable.class);
  }

  /**
   * Convert an instance of Renewable to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

