/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import java.util.Arrays;
import cloud.neice.model.CertificateCode;
import cloud.neice.model.Result;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseOfCertificateCode
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-31T09:30:11.322380+08:00[Asia/Shanghai]")
public class ResponseOfCertificateCode {
  /**
   * Gets or Sets action
   */
  @JsonAdapter(ActionEnum.Adapter.class)
  public enum ActionEnum {
    GET_AES_KEY("GET_AES_KEY"),
    
    NONE("NONE"),
    
    REFRESH_SERVER_PUBLIC_KEY("REFRESH_SERVER_PUBLIC_KEY"),
    
    RETRY_LATER("RETRY_LATER"),
    
    RE_LOGIN("RE_LOGIN"),
    
    UPDATE_CLIENT_VERSION("UPDATE_CLIENT_VERSION"),
    
    UPLOAD_CLIENT_PUBLIC_KEY("UPLOAD_CLIENT_PUBLIC_KEY");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ActionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ActionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ActionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ActionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private ActionEnum action;

  public static final String SERIALIZED_NAME_ALGORITHM = "algorithm";
  @SerializedName(SERIALIZED_NAME_ALGORITHM)
  private String algorithm;

  public static final String SERIALIZED_NAME_CIPHERTEXT = "ciphertext";
  @SerializedName(SERIALIZED_NAME_CIPHERTEXT)
  private String ciphertext;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private CertificateCode data;

  /**
   * Gets or Sets error
   */
  @JsonAdapter(ErrorEnum.Adapter.class)
  public enum ErrorEnum {
    ACCEPTED("ACCEPTED"),
    
    ACCESS_RATE_LIMIT("ACCESS_RATE_LIMIT"),
    
    ACCOUNT_CANCELLED("ACCOUNT_CANCELLED"),
    
    ACCOUNT_DISABLED("ACCOUNT_DISABLED"),
    
    ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
    
    ACCOUNT_NOT_ACTIVATED("ACCOUNT_NOT_ACTIVATED"),
    
    AES_DECRYPTED_DATA_EMPTY("AES_DECRYPTED_DATA_EMPTY"),
    
    AES_DECRYPT_FAILED("AES_DECRYPT_FAILED"),
    
    AES_ENCRYPTED_DATA_EMPTY("AES_ENCRYPTED_DATA_EMPTY"),
    
    AES_ENCRYPT_FAILED("AES_ENCRYPT_FAILED"),
    
    AES_KEY_EXPIRED("AES_KEY_EXPIRED"),
    
    AES_KEY_EXPIRING_SOON("AES_KEY_EXPIRING_SOON"),
    
    AES_KEY_FORMAT_ERROR("AES_KEY_FORMAT_ERROR"),
    
    AES_KEY_GENERATE_FAILED("AES_KEY_GENERATE_FAILED"),
    
    AES_KEY_LENGTH_ERROR("AES_KEY_LENGTH_ERROR"),
    
    AES_KEY_NOT_FOUND("AES_KEY_NOT_FOUND"),
    
    AES_MODE_NOT_SUPPORTED("AES_MODE_NOT_SUPPORTED"),
    
    AES_PADDING_NOT_SUPPORTED("AES_PADDING_NOT_SUPPORTED"),
    
    AES_VECTOR_FORMAT_ERROR("AES_VECTOR_FORMAT_ERROR"),
    
    AES_VECTOR_LENGTH_ERROR("AES_VECTOR_LENGTH_ERROR"),
    
    ALREADY_REPORTED("ALREADY_REPORTED"),
    
    BAD_GATEWAY("BAD_GATEWAY"),
    
    BAD_REQUEST("BAD_REQUEST"),
    
    BUSINESS_ERROR("BUSINESS_ERROR"),
    
    CAPTCHA_ERROR("CAPTCHA_ERROR"),
    
    CAPTCHA_EXPIRED("CAPTCHA_EXPIRED"),
    
    CONFLICT("CONFLICT"),
    
    CONTINUE("CONTINUE"),
    
    CREATED("CREATED"),
    
    DATABASE_BACKUP_FAILED("DATABASE_BACKUP_FAILED"),
    
    DATABASE_CHECK_CONSTRAINT_VIOLATION("DATABASE_CHECK_CONSTRAINT_VIOLATION"),
    
    DATABASE_COLUMN_NOT_FOUND("DATABASE_COLUMN_NOT_FOUND"),
    
    DATABASE_CONNECTION_FAILED("DATABASE_CONNECTION_FAILED"),
    
    DATABASE_CONNECTION_POOL_EXHAUSTED("DATABASE_CONNECTION_POOL_EXHAUSTED"),
    
    DATABASE_DEADLOCK("DATABASE_DEADLOCK"),
    
    DATABASE_DELETE_FAILED("DATABASE_DELETE_FAILED"),
    
    DATABASE_DUPLICATE_KEY("DATABASE_DUPLICATE_KEY"),
    
    DATABASE_FOREIGN_KEY_VIOLATION("DATABASE_FOREIGN_KEY_VIOLATION"),
    
    DATABASE_INDEX_NOT_FOUND("DATABASE_INDEX_NOT_FOUND"),
    
    DATABASE_INSERT_FAILED("DATABASE_INSERT_FAILED"),
    
    DATABASE_NOT_NULL_VIOLATION("DATABASE_NOT_NULL_VIOLATION"),
    
    DATABASE_OPERATION_FAILED("DATABASE_OPERATION_FAILED"),
    
    DATABASE_PERMISSION_DENIED("DATABASE_PERMISSION_DENIED"),
    
    DATABASE_QUERY_FAILED("DATABASE_QUERY_FAILED"),
    
    DATABASE_READ_ONLY("DATABASE_READ_ONLY"),
    
    DATABASE_RESTORE_FAILED("DATABASE_RESTORE_FAILED"),
    
    DATABASE_SQL_SYNTAX_ERROR("DATABASE_SQL_SYNTAX_ERROR"),
    
    DATABASE_TABLE_NOT_FOUND("DATABASE_TABLE_NOT_FOUND"),
    
    DATABASE_TIMEOUT("DATABASE_TIMEOUT"),
    
    DATABASE_TRANSACTION_FAILED("DATABASE_TRANSACTION_FAILED"),
    
    DATABASE_UNIQUE_CONSTRAINT_VIOLATION("DATABASE_UNIQUE_CONSTRAINT_VIOLATION"),
    
    DATABASE_UPDATE_FAILED("DATABASE_UPDATE_FAILED"),
    
    DATABASE_VERSION_INCOMPATIBLE("DATABASE_VERSION_INCOMPATIBLE"),
    
    DATA_ALREADY_EXISTS("DATA_ALREADY_EXISTS"),
    
    DATA_CONSTRAINT_VIOLATION("DATA_CONSTRAINT_VIOLATION"),
    
    DATA_FORMAT_ERROR("DATA_FORMAT_ERROR"),
    
    DATA_INTEGRITY_ERROR("DATA_INTEGRITY_ERROR"),
    
    DATA_NOT_FOUND("DATA_NOT_FOUND"),
    
    DATA_RANGE_ERROR("DATA_RANGE_ERROR"),
    
    DATA_RELATION_ERROR("DATA_RELATION_ERROR"),
    
    DATA_STATUS_ERROR("DATA_STATUS_ERROR"),
    
    DATA_VERSION_CONFLICT("DATA_VERSION_CONFLICT"),
    
    EARLY_HINTS("EARLY_HINTS"),
    
    EXPECTATION_FAILED("EXPECTATION_FAILED"),
    
    FAILED_DEPENDENCY("FAILED_DEPENDENCY"),
    
    FEATURE_NOT_AVAILABLE("FEATURE_NOT_AVAILABLE"),
    
    FORBIDDEN("FORBIDDEN"),
    
    FORCE_ENCRYPT_REQUEST_REQUIRED("FORCE_ENCRYPT_REQUEST_REQUIRED"),
    
    FORCE_ENCRYPT_SESSION_REQUIRED("FORCE_ENCRYPT_SESSION_REQUIRED"),
    
    FOUND("FOUND"),
    
    GATEWAY_TIMEOUT("GATEWAY_TIMEOUT"),
    
    GONE("GONE"),
    
    HTTP_VERSION_NOT_SUPPORTED("HTTP_VERSION_NOT_SUPPORTED"),
    
    IM_USED("IM_USED"),
    
    INSUFFICIENT_STORAGE("INSUFFICIENT_STORAGE"),
    
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    
    IP_FORBIDDEN("IP_FORBIDDEN"),
    
    LENGTH_REQUIRED("LENGTH_REQUIRED"),
    
    LOCKED("LOCKED"),
    
    LOGIN_EXPIRED("LOGIN_EXPIRED"),
    
    LOGIN_FAILED("LOGIN_FAILED"),
    
    LOOP_DETECTED("LOOP_DETECTED"),
    
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    
    MOVED_PERMANENTLY("MOVED_PERMANENTLY"),
    
    MULTIPLE_CHOICES("MULTIPLE_CHOICES"),
    
    MULTI_STATUS("MULTI_STATUS"),
    
    NETWORK_AUTHENTICATION_REQUIRED("NETWORK_AUTHENTICATION_REQUIRED"),
    
    NON_AUTHORITATIVE_INFORMATION("NON_AUTHORITATIVE_INFORMATION"),
    
    NOT_ACCEPTABLE("NOT_ACCEPTABLE"),
    
    NOT_EXTENDED("NOT_EXTENDED"),
    
    NOT_FOUND("NOT_FOUND"),
    
    NOT_IMPLEMENTED("NOT_IMPLEMENTED"),
    
    NOT_MODIFIED("NOT_MODIFIED"),
    
    NO_CONTENT("NO_CONTENT"),
    
    OK("OK"),
    
    OPERATION_NOT_ALLOWED("OPERATION_NOT_ALLOWED"),
    
    OPERATION_TIMEOUT("OPERATION_TIMEOUT"),
    
    PARTIAL_CONTENT("PARTIAL_CONTENT"),
    
    PASSWORD_EXPIRED("PASSWORD_EXPIRED"),
    
    PASSWORD_WEAK("PASSWORD_WEAK"),
    
    PAYLOAD_TOO_LARGE("PAYLOAD_TOO_LARGE"),
    
    PAYMENT_REQUIRED("PAYMENT_REQUIRED"),
    
    PERMANENT_REDIRECT("PERMANENT_REDIRECT"),
    
    PERMISSION_DENIED("PERMISSION_DENIED"),
    
    PRECONDITION_FAILED("PRECONDITION_FAILED"),
    
    PRECONDITION_REQUIRED("PRECONDITION_REQUIRED"),
    
    PROCESSING("PROCESSING"),
    
    PROXY_AUTHENTICATION_REQUIRED("PROXY_AUTHENTICATION_REQUIRED"),
    
    RANGE_NOT_SATISFIABLE("RANGE_NOT_SATISFIABLE"),
    
    REFRESH_TOKEN_EXPIRED("REFRESH_TOKEN_EXPIRED"),
    
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID"),
    
    REQUEST_HEADER_FIELDS_TOO_LARGE("REQUEST_HEADER_FIELDS_TOO_LARGE"),
    
    REQUEST_TIMEOUT("REQUEST_TIMEOUT"),
    
    RESET_CONTENT("RESET_CONTENT"),
    
    RESOURCE_LOCKED("RESOURCE_LOCKED"),
    
    RSA_CLIENT_PUBLIC_KEY_EXPIRING_SOON("RSA_CLIENT_PUBLIC_KEY_EXPIRING_SOON"),
    
    RSA_CLIENT_PUBLIC_KEY_NOT_FOUND("RSA_CLIENT_PUBLIC_KEY_NOT_FOUND"),
    
    RSA_DECRYPT_FAILED("RSA_DECRYPT_FAILED"),
    
    RSA_ENCRYPT_FAILED("RSA_ENCRYPT_FAILED"),
    
    RSA_KEY_FORMAT_ERROR("RSA_KEY_FORMAT_ERROR"),
    
    RSA_KEY_GENERATE_FAILED("RSA_KEY_GENERATE_FAILED"),
    
    RSA_KEY_LENGTH_ERROR("RSA_KEY_LENGTH_ERROR"),
    
    RSA_KEY_PAIR_EXPIRING_SOON("RSA_KEY_PAIR_EXPIRING_SOON"),
    
    RSA_KEY_PAIR_MISMATCH("RSA_KEY_PAIR_MISMATCH"),
    
    RSA_KEY_PAIR_NOT_FOUND("RSA_KEY_PAIR_NOT_FOUND"),
    
    RSA_PRIVATE_KEY_NOT_FOUND("RSA_PRIVATE_KEY_NOT_FOUND"),
    
    RSA_PRIVATE_KEY_PARSE_ERROR("RSA_PRIVATE_KEY_PARSE_ERROR"),
    
    RSA_PUBLIC_KEY_PARSE_ERROR("RSA_PUBLIC_KEY_PARSE_ERROR"),
    
    RSA_SESSION_INVALID("RSA_SESSION_INVALID"),
    
    RSA_SESSION_REQUIRED("RSA_SESSION_REQUIRED"),
    
    SEE_OTHER("SEE_OTHER"),
    
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    
    SESSION_EXPIRED("SESSION_EXPIRED"),
    
    SESSION_INVALID("SESSION_INVALID"),
    
    SUCCESS("SUCCESS"),
    
    SWITCHING_PROTOCOLS("SWITCHING_PROTOCOLS"),
    
    SYSTEM_MAINTENANCE("SYSTEM_MAINTENANCE"),
    
    TEMPORARY_REDIRECT("TEMPORARY_REDIRECT"),
    
    THIRD_PARTY_LOGIN_FAILED("THIRD_PARTY_LOGIN_FAILED"),
    
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    
    TOKEN_INVALID("TOKEN_INVALID"),
    
    TOO_EARLY("TOO_EARLY"),
    
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),
    
    UNAUTHORIZED("UNAUTHORIZED"),
    
    UNAVAILABLE_FOR_LEGAL_REASONS("UNAVAILABLE_FOR_LEGAL_REASONS"),
    
    UNKNOWN_ERROR("UNKNOWN_ERROR"),
    
    UNPROCESSABLE_ENTITY("UNPROCESSABLE_ENTITY"),
    
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    
    UPGRADE_REQUIRED("UPGRADE_REQUIRED"),
    
    URI_TOO_LONG("URI_TOO_LONG"),
    
    USER_NOT_LOGIN("USER_NOT_LOGIN"),
    
    USE_PROXY("USE_PROXY"),
    
    VARIANT_ALSO_NEGOTIATES("VARIANT_ALSO_NEGOTIATES"),
    
    VERSION_INCOMPATIBLE("VERSION_INCOMPATIBLE");

    private String value;

    ErrorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ErrorEnum fromValue(String value) {
      for (ErrorEnum b : ErrorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ErrorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ErrorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ErrorEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ErrorEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private ErrorEnum error;

  public static final String SERIALIZED_NAME_MSG = "msg";
  @SerializedName(SERIALIZED_NAME_MSG)
  private String msg;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private Result result;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  private String session;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success;


  public ResponseOfCertificateCode action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public ResponseOfCertificateCode algorithm(String algorithm) {
    
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAlgorithm() {
    return algorithm;
  }


  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }


  public ResponseOfCertificateCode ciphertext(String ciphertext) {
    
    this.ciphertext = ciphertext;
    return this;
  }

   /**
   * Get ciphertext
   * @return ciphertext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCiphertext() {
    return ciphertext;
  }


  public void setCiphertext(String ciphertext) {
    this.ciphertext = ciphertext;
  }


  public ResponseOfCertificateCode code(Integer code) {
    
    this.code = code;
    return this;
  }

   /**
   * 响应代码
   * @return code
  **/
  @ApiModelProperty(required = true, value = "响应代码")

  public Integer getCode() {
    return code;
  }


  public void setCode(Integer code) {
    this.code = code;
  }


  public ResponseOfCertificateCode data(CertificateCode data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CertificateCode getData() {
    return data;
  }


  public void setData(CertificateCode data) {
    this.data = data;
  }


  public ResponseOfCertificateCode error(ErrorEnum error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ErrorEnum getError() {
    return error;
  }


  public void setError(ErrorEnum error) {
    this.error = error;
  }


  public ResponseOfCertificateCode msg(String msg) {
    
    this.msg = msg;
    return this;
  }

   /**
   * 错误信息:成功时为空或为success
   * @return msg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "错误信息:成功时为空或为success")

  public String getMsg() {
    return msg;
  }


  public void setMsg(String msg) {
    this.msg = msg;
  }


  public ResponseOfCertificateCode result(Result result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Result getResult() {
    return result;
  }


  public void setResult(Result result) {
    this.result = result;
  }


  public ResponseOfCertificateCode session(String session) {
    
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSession() {
    return session;
  }


  public void setSession(String session) {
    this.session = session;
  }


  public ResponseOfCertificateCode success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    this.success = success;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseOfCertificateCode responseOfCertificateCode = (ResponseOfCertificateCode) o;
    return Objects.equals(this.action, responseOfCertificateCode.action) &&
        Objects.equals(this.algorithm, responseOfCertificateCode.algorithm) &&
        Objects.equals(this.ciphertext, responseOfCertificateCode.ciphertext) &&
        Objects.equals(this.code, responseOfCertificateCode.code) &&
        Objects.equals(this.data, responseOfCertificateCode.data) &&
        Objects.equals(this.error, responseOfCertificateCode.error) &&
        Objects.equals(this.msg, responseOfCertificateCode.msg) &&
        Objects.equals(this.result, responseOfCertificateCode.result) &&
        Objects.equals(this.session, responseOfCertificateCode.session) &&
        Objects.equals(this.success, responseOfCertificateCode.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, algorithm, ciphertext, code, data, error, msg, result, session, success);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseOfCertificateCode {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    ciphertext: ").append(toIndentedString(ciphertext)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

