/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.neice.JSON;

/**
 * Status
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Status {
  public static final String SERIALIZED_NAME_BLIND = "blind";
  @SerializedName(SERIALIZED_NAME_BLIND)
  @jakarta.annotation.Nullable
  private Boolean blind;

  public static final String SERIALIZED_NAME_BLIND_RESERVE = "blindReserve";
  @SerializedName(SERIALIZED_NAME_BLIND_RESERVE)
  @jakarta.annotation.Nullable
  private Boolean blindReserve;

  public static final String SERIALIZED_NAME_BLIND_RESERVE_UNIT = "blindReserveUnit";
  @SerializedName(SERIALIZED_NAME_BLIND_RESERVE_UNIT)
  @jakarta.annotation.Nullable
  private BigDecimal blindReserveUnit;

  public static final String SERIALIZED_NAME_BLIND_UNIT = "blindUnit";
  @SerializedName(SERIALIZED_NAME_BLIND_UNIT)
  @jakarta.annotation.Nullable
  private BigDecimal blindUnit;

  public static final String SERIALIZED_NAME_MAGIC = "magic";
  @SerializedName(SERIALIZED_NAME_MAGIC)
  @jakarta.annotation.Nullable
  private Boolean magic;

  public static final String SERIALIZED_NAME_MAGIC_UNIT = "magicUnit";
  @SerializedName(SERIALIZED_NAME_MAGIC_UNIT)
  @jakarta.annotation.Nullable
  private BigDecimal magicUnit;

  public static final String SERIALIZED_NAME_QUICK = "quick";
  @SerializedName(SERIALIZED_NAME_QUICK)
  @jakarta.annotation.Nullable
  private Boolean quick;

  public static final String SERIALIZED_NAME_QUICK_UNIT = "quickUnit";
  @SerializedName(SERIALIZED_NAME_QUICK_UNIT)
  @jakarta.annotation.Nullable
  private BigDecimal quickUnit;

  public static final String SERIALIZED_NAME_RESERVE = "reserve";
  @SerializedName(SERIALIZED_NAME_RESERVE)
  @jakarta.annotation.Nullable
  private Boolean reserve;

  public static final String SERIALIZED_NAME_RESERVE_UNIT = "reserveUnit";
  @SerializedName(SERIALIZED_NAME_RESERVE_UNIT)
  @jakarta.annotation.Nullable
  private BigDecimal reserveUnit;

  public Status() {
  }

  public Status blind(@jakarta.annotation.Nullable Boolean blind) {
    this.blind = blind;
    return this;
  }

  /**
   * 标记该系统是否支持盲盒设备证书能立即秒出激活的功能
   * @return blind
   */
  @jakarta.annotation.Nullable
  public Boolean getBlind() {
    return blind;
  }

  public void setBlind(@jakarta.annotation.Nullable Boolean blind) {
    this.blind = blind;
  }


  public Status blindReserve(@jakarta.annotation.Nullable Boolean blindReserve) {
    this.blindReserve = blindReserve;
    return this;
  }

  /**
   * 标记该系统是否支持盲盒预定设备证书的功能
   * @return blindReserve
   */
  @jakarta.annotation.Nullable
  public Boolean getBlindReserve() {
    return blindReserve;
  }

  public void setBlindReserve(@jakarta.annotation.Nullable Boolean blindReserve) {
    this.blindReserve = blindReserve;
  }


  public Status blindReserveUnit(@jakarta.annotation.Nullable BigDecimal blindReserveUnit) {
    this.blindReserveUnit = blindReserveUnit;
    return this;
  }

  /**
   * 盲盒预定证书服务单价
   * @return blindReserveUnit
   */
  @jakarta.annotation.Nullable
  public BigDecimal getBlindReserveUnit() {
    return blindReserveUnit;
  }

  public void setBlindReserveUnit(@jakarta.annotation.Nullable BigDecimal blindReserveUnit) {
    this.blindReserveUnit = blindReserveUnit;
  }


  public Status blindUnit(@jakarta.annotation.Nullable BigDecimal blindUnit) {
    this.blindUnit = blindUnit;
    return this;
  }

  /**
   * 盲盒秒出证书单价
   * @return blindUnit
   */
  @jakarta.annotation.Nullable
  public BigDecimal getBlindUnit() {
    return blindUnit;
  }

  public void setBlindUnit(@jakarta.annotation.Nullable BigDecimal blindUnit) {
    this.blindUnit = blindUnit;
  }


  public Status magic(@jakarta.annotation.Nullable Boolean magic) {
    this.magic = magic;
    return this;
  }

  /**
   * 标记该系统是否支持部分设备证书能秒出激活的功能
   * @return magic
   */
  @jakarta.annotation.Nullable
  public Boolean getMagic() {
    return magic;
  }

  public void setMagic(@jakarta.annotation.Nullable Boolean magic) {
    this.magic = magic;
  }


  public Status magicUnit(@jakarta.annotation.Nullable BigDecimal magicUnit) {
    this.magicUnit = magicUnit;
    return this;
  }

  /**
   * 部分秒出证书单价
   * @return magicUnit
   */
  @jakarta.annotation.Nullable
  public BigDecimal getMagicUnit() {
    return magicUnit;
  }

  public void setMagicUnit(@jakarta.annotation.Nullable BigDecimal magicUnit) {
    this.magicUnit = magicUnit;
  }


  public Status quick(@jakarta.annotation.Nullable Boolean quick) {
    this.quick = quick;
    return this;
  }

  /**
   * 标记该系统是否支持全部设备证书能立即秒出激活的功能
   * @return quick
   */
  @jakarta.annotation.Nullable
  public Boolean getQuick() {
    return quick;
  }

  public void setQuick(@jakarta.annotation.Nullable Boolean quick) {
    this.quick = quick;
  }


  public Status quickUnit(@jakarta.annotation.Nullable BigDecimal quickUnit) {
    this.quickUnit = quickUnit;
    return this;
  }

  /**
   * 全量秒出证书单价
   * @return quickUnit
   */
  @jakarta.annotation.Nullable
  public BigDecimal getQuickUnit() {
    return quickUnit;
  }

  public void setQuickUnit(@jakarta.annotation.Nullable BigDecimal quickUnit) {
    this.quickUnit = quickUnit;
  }


  public Status reserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
    return this;
  }

  /**
   * 标记该系统是否支持预定设备证书的功能
   * @return reserve
   */
  @jakarta.annotation.Nullable
  public Boolean getReserve() {
    return reserve;
  }

  public void setReserve(@jakarta.annotation.Nullable Boolean reserve) {
    this.reserve = reserve;
  }


  public Status reserveUnit(@jakarta.annotation.Nullable BigDecimal reserveUnit) {
    this.reserveUnit = reserveUnit;
    return this;
  }

  /**
   * 预定证书服务单价
   * @return reserveUnit
   */
  @jakarta.annotation.Nullable
  public BigDecimal getReserveUnit() {
    return reserveUnit;
  }

  public void setReserveUnit(@jakarta.annotation.Nullable BigDecimal reserveUnit) {
    this.reserveUnit = reserveUnit;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Status status = (Status) o;
    return Objects.equals(this.blind, status.blind) &&
        Objects.equals(this.blindReserve, status.blindReserve) &&
        Objects.equals(this.blindReserveUnit, status.blindReserveUnit) &&
        Objects.equals(this.blindUnit, status.blindUnit) &&
        Objects.equals(this.magic, status.magic) &&
        Objects.equals(this.magicUnit, status.magicUnit) &&
        Objects.equals(this.quick, status.quick) &&
        Objects.equals(this.quickUnit, status.quickUnit) &&
        Objects.equals(this.reserve, status.reserve) &&
        Objects.equals(this.reserveUnit, status.reserveUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blind, blindReserve, blindReserveUnit, blindUnit, magic, magicUnit, quick, quickUnit, reserve, reserveUnit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Status {\n");
    sb.append("    blind: ").append(toIndentedString(blind)).append("\n");
    sb.append("    blindReserve: ").append(toIndentedString(blindReserve)).append("\n");
    sb.append("    blindReserveUnit: ").append(toIndentedString(blindReserveUnit)).append("\n");
    sb.append("    blindUnit: ").append(toIndentedString(blindUnit)).append("\n");
    sb.append("    magic: ").append(toIndentedString(magic)).append("\n");
    sb.append("    magicUnit: ").append(toIndentedString(magicUnit)).append("\n");
    sb.append("    quick: ").append(toIndentedString(quick)).append("\n");
    sb.append("    quickUnit: ").append(toIndentedString(quickUnit)).append("\n");
    sb.append("    reserve: ").append(toIndentedString(reserve)).append("\n");
    sb.append("    reserveUnit: ").append(toIndentedString(reserveUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("blind");
    openapiFields.add("blindReserve");
    openapiFields.add("blindReserveUnit");
    openapiFields.add("blindUnit");
    openapiFields.add("magic");
    openapiFields.add("magicUnit");
    openapiFields.add("quick");
    openapiFields.add("quickUnit");
    openapiFields.add("reserve");
    openapiFields.add("reserveUnit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Status
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Status.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Status is not found in the empty JSON string", Status.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Status.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Status` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Status.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Status' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Status> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Status.class));

       return (TypeAdapter<T>) new TypeAdapter<Status>() {
           @Override
           public void write(JsonWriter out, Status value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Status read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Status given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Status
   * @throws IOException if the JSON string is invalid with respect to Status
   */
  public static Status fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Status.class);
  }

  /**
   * Convert an instance of Status to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

