/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OpenEnterpriseCertificate
 */
public class OpenEnterpriseCertificateTest {
    private final OpenEnterpriseCertificate model = new OpenEnterpriseCertificate();

    /**
     * Model tests for OpenEnterpriseCertificate
     */
    @Test
    public void testOpenEnterpriseCertificate() {
        // TODO: test OpenEnterpriseCertificate
    }

    /**
     * Test the property 'certificate'
     */
    @Test
    public void certificateTest() {
        // TODO: test certificate
    }

    /**
     * Test the property 'certificateName'
     */
    @Test
    public void certificateNameTest() {
        // TODO: test certificateName
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'issuerDn'
     */
    @Test
    public void issuerDnTest() {
        // TODO: test issuerDn
    }

    /**
     * Test the property 'md5'
     */
    @Test
    public void md5Test() {
        // TODO: test md5
    }

    /**
     * Test the property 'mobileprovision'
     */
    @Test
    public void mobileprovisionTest() {
        // TODO: test mobileprovision
    }

    /**
     * Test the property 'notAfter'
     */
    @Test
    public void notAfterTest() {
        // TODO: test notAfter
    }

    /**
     * Test the property 'notBefore'
     */
    @Test
    public void notBeforeTest() {
        // TODO: test notBefore
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'revocationReason'
     */
    @Test
    public void revocationReasonTest() {
        // TODO: test revocationReason
    }

    /**
     * Test the property 'revocationTime'
     */
    @Test
    public void revocationTimeTest() {
        // TODO: test revocationTime
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'subjectDn'
     */
    @Test
    public void subjectDnTest() {
        // TODO: test subjectDn
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

}
