/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PersonalCertificate
 */
public class PersonalCertificateTest {
    private final PersonalCertificate model = new PersonalCertificate();

    /**
     * Model tests for PersonalCertificate
     */
    @Test
    public void testPersonalCertificate() {
        // TODO: test PersonalCertificate
    }

    /**
     * Test the property 'certificate'
     */
    @Test
    public void certificateTest() {
        // TODO: test certificate
    }

    /**
     * Test the property 'certificateId'
     */
    @Test
    public void certificateIdTest() {
        // TODO: test certificateId
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    public void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'mobileprovision'
     */
    @Test
    public void mobileprovisionTest() {
        // TODO: test mobileprovision
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'quality'
     */
    @Test
    public void qualityTest() {
        // TODO: test quality
    }

    /**
     * Test the property 'qualityTime'
     */
    @Test
    public void qualityTimeTest() {
        // TODO: test qualityTime
    }

    /**
     * Test the property 'refer'
     */
    @Test
    public void referTest() {
        // TODO: test refer
    }

    /**
     * Test the property 'reserve'
     */
    @Test
    public void reserveTest() {
        // TODO: test reserve
    }

    /**
     * Test the property 'udid'
     */
    @Test
    public void udidTest() {
        // TODO: test udid
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

}
