/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Status
 */
public class StatusTest {
    private final Status model = new Status();

    /**
     * Model tests for Status
     */
    @Test
    public void testStatus() {
        // TODO: test Status
    }

    /**
     * Test the property 'blind'
     */
    @Test
    public void blindTest() {
        // TODO: test blind
    }

    /**
     * Test the property 'blindReserve'
     */
    @Test
    public void blindReserveTest() {
        // TODO: test blindReserve
    }

    /**
     * Test the property 'blindReserveUnit'
     */
    @Test
    public void blindReserveUnitTest() {
        // TODO: test blindReserveUnit
    }

    /**
     * Test the property 'blindUnit'
     */
    @Test
    public void blindUnitTest() {
        // TODO: test blindUnit
    }

    /**
     * Test the property 'magic'
     */
    @Test
    public void magicTest() {
        // TODO: test magic
    }

    /**
     * Test the property 'magicUnit'
     */
    @Test
    public void magicUnitTest() {
        // TODO: test magicUnit
    }

    /**
     * Test the property 'quick'
     */
    @Test
    public void quickTest() {
        // TODO: test quick
    }

    /**
     * Test the property 'quickUnit'
     */
    @Test
    public void quickUnitTest() {
        // TODO: test quickUnit
    }

    /**
     * Test the property 'reserve'
     */
    @Test
    public void reserveTest() {
        // TODO: test reserve
    }

    /**
     * Test the property 'reserveUnit'
     */
    @Test
    public void reserveUnitTest() {
        // TODO: test reserveUnit
    }

}
