/*
 * 内测云分发开发者API接口
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.neice.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Version
 */
public class VersionTest {
    private final Version model = new Version();

    /**
     * Model tests for Version
     */
    @Test
    public void testVersion() {
        // TODO: test Version
    }

    /**
     * Test the property 'build'
     */
    @Test
    public void buildTest() {
        // TODO: test build
    }

    /**
     * Test the property 'major'
     */
    @Test
    public void majorTest() {
        // TODO: test major
    }

    /**
     * Test the property 'minor'
     */
    @Test
    public void minorTest() {
        // TODO: test minor
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

}
